
/**
 * Dynamic microcopy for AI helper tiles.
 * 100+ unique messages for each tile, covering different intents and time-of-day tones.
 */

export const TILE_1_MESSAGES = [
    "Find the right words for that message you’ve been putting off. We can help you say exactly what you mean.",
    "Start your morning with a clear head. Tell us what’s on your mind and we’ll help you organize it.",
    "Got a complicated topic to wrap your head around? We can break it down into plain English for you.",
    "When you’re not sure how to start, just say hello. We’re great at getting things moving.",
    "Let us take the heavy lifting out of your rough drafts. One quick chat can change your whole afternoon.",
    "A fresh perspective on your plans for the week. Sometimes a second set of eyes makes all the difference.",
    "Take the guesswork out of your next big decision. Review the pros and cons in a quiet space.",
    "Whether it’s a friendly note or a formal request, we’ll help you find a tone that feels just right.",
    "Clear away the mental fog before you get started. A little help goes a long way.",
    "Trying to explain something tricky to a friend? Let’s walk through it together first.",
    "Give your brain a rest. Tell us what you need and watch the pieces fall into place.",
    "Don't let a blank page slow you down. We can help you find that first sentence.",
    "Make sense of the things that feel a bit overwhelming. Clarity is just a conversation away.",
    "Settle in and talk through your ideas. We're here to listen and help you refine them.",
    "Need a hand with a difficult reply? We can help you keep it calm and clear.",
    "Your silent partner for a busy midday. Check things off your list with a bit more ease.",
    "When you’re stuck on \"what next,\" we’ve got a few ideas. Let's figure out the first step together.",
    "A gentle way to get your thoughts in order. Perfect for a quiet morning at your desk.",
    "Don't overthink the small stuff. We can handle the wording while you focus on the big picture.",
    "A helpful presence for your most creative ideas. Let’s see where the conversation takes us.",
    "Simplify the complicated. We’ll help you see the path forward when things feel messy.",
    "Tired of staring at your inbox? We can help you find a polite way to say no.",
    "A calm space for your biggest questions. No noise, just helpful answers.",
    "When you're multi-tasking and need a shortcut, we're here to help you stay on track.",
    "Wrap up your day with a sense of accomplishment. We’ll help you summarize your notes so you can switch off.",
    "Just type what you're thinking. We’ll help you turn jumbled thoughts into a solid plan.",
    "A friendly nudge when you’re feeling uninspired. Let's find something new to explore.",
    "Keep your cool during a stressful project. We can help you stay organized and focused.",
    "From grocery lists to travel itineraries, we’ll help you fill in the blanks.",
    "Your go-to for a quick sanity check. Is this message too long? Let’s find out.",
    "Early morning clarity for a long day ahead. Let’s get your priorities straight.",
    "Practical help for the middle of your work session. Get to the point faster with a little assistance.",
    "Relax and let us do the drafting for you. The easiest way to get your thoughts on paper.",
    "A thoughtful way to spend a few minutes. Let’s explore a topic you’ve always been curious about.",
    "Don’t let the details trip you up. We’ll help you keep everything in perspective.",
    "Focus on the heart of the matter. We’ll take care of the phrasing and the structure.",
    "A simple way to feel more prepared. Outline your thoughts before the big meeting starts.",
    "When the right word is on the tip of your tongue, we’ll help you find it.",
    "A peaceful conversation to end your evening. Finalize your plans so you can sleep soundly.",
    "Bridge the gap between a rough idea and a finished thought. We’re here to help you get there.",
    "Get unstuck in seconds. A quick back-and-forth can clear up any confusion.",
    "Your personal proofreader and brainstorming partner. Ready whenever you are.",
    "Clear, polite, and effective. We’ll help you communicate with confidence.",
    "Find a better way to say \"per my last email.\" We've got you covered.",
    "Start your project with a bit of momentum. A few suggestions to get the ball rolling.",
    "Helpful, human, and always available. Your quiet assistant for everyday tasks.",
    "When you can't find the motivation to start, we'll help you find an easy way in.",
    "A different angle on an old problem. Fresh ideas for your most stubborn tasks.",
    "The most direct path to a finished draft. Tell us the basics and we'll do the rest.",
    "Wind down with a little help. Organize your thoughts for tomorrow so you can rest tonight.",
    "Start your morning by seeing the big picture. We'll help you map out your day.",
    "Practical solutions for your busiest moments. Less thinking, more doing.",
    "A calming influence when things get hectic. Let’s simplify your to-do list together.",
    "Say it better with a little support. We'll help you strike the perfect balance.",
    "A second opinion that's always ready to help. Refine your ideas in real-time.",
    "Don't let a confusing topic ruin your afternoon. We'll explain it in a way that makes sense.",
    "Small steps lead to big successes. Let’s figure out what those small steps look like.",
    "A reliable partner for your everyday writing. Clear, concise, and helpful.",
    "Get your thoughts out of your head and onto the screen. We'll help you organize them as you go.",
    "Perfect for the moments when you just need a hint. We've got plenty of ideas to share.",
    "Ease into your morning with a little guidance. Let's make today feel manageable.",
    "Efficiency for your midday rush. Get the answers you need without the wait.",
    "A soft place to land after a busy day. Let’s wrap up your loose ends together.",
    "Polished and professional, or warm and friendly. We’ll help you find the right tone for any occasion.",
    "When you're struggling to find the right opening line, we'll give you a few options to choose from.",
    "Make sense of the information overload. We'll help you focus on what really matters.",
    "A simple way to get more done with less stress. Let us handle the details.",
    "Build your confidence before you hit send. We'll help you double-check your message.",
    "A fresh pair of eyes for your creative projects. Let's see what we can build together.",
    "The quickest way to get from a \"maybe\" to a \"yes.\" Let’s look at your options.",
    "Start your day on a positive note. We’ll help you organize your most important tasks.",
    "No-nonsense help for your practical questions. Get straight to the point.",
    "A quiet summary for a busy day. See what you've accomplished and what's next.",
    "Whatever you’re writing, we can help you make it better. Let’s work on your draft together.",
    "A fountain of ideas for your next gathering. We’ll help you plan the perfect event.",
    "When you're feeling a bit lost, we're here to help you find your way. Let's look at the situation differently.",
    "A reliable resource for your most curious moments. Always here to help you learn something new.",
    "Save time and mental energy on your daily chores. We'll help you stay organized.",
    "The easy way to find your voice. We’ll help you express yourself clearly and kindly.",
    "Relax your mind and let us take over for a bit. The phrasing is on us.",
    "Morning inspiration for your most ambitious goals. Let's dream big together.",
    "Steady support for your afternoon tasks. Keep your momentum going.",
    "Clear the decks for a restful night. We'll help you settle your final thoughts.",
    "A helpful hand for those long, confusing forms. We can help you figure out what they’re asking.",
    "When you need a quick reply, we've got one ready. Short, sweet, and to the point.",
    "The smartest way to compare your choices. We'll help you see the pros and cons clearly.",
    "A supportive presence for your learning journey. Ask us anything, anytime.",
    "Don't let the technical bits get in the way. We'll help you focus on the human side of things.",
    "A simple conversation that leads to great things. Let's see where your curiosity takes us.",
    "The easiest way to get your thoughts in a row. One line at a time.",
    "Start your morning with a sense of calm. We'll help you organize the chaos.",
    "Practical tips for your busy life. Little helps that make a big difference.",
    "A reflective space for your evening thoughts. Let's look back on what worked today.",
    "When you have the idea but not the words, we'll help you bridge the gap.",
    "A friendly partner for your most mundane tasks. Everything is easier with a little help.",
    "The most human way to get things done online. Just ask, and we'll help.",
    "A trusted companion for your daily decisions. Clear, helpful, and kind.",
    "Don't let the stress of a blank email stop you. We'll help you find the right start.",
    "A quiet moment of clarity in a noisy world. Let's focus on one thing at a time.",
    "End your day with a clear mind and a solid plan. Tomorrow is looking bright."
];

export const TILE_2_MESSAGES = [
    "Stop digging through endless results. Get the answer you need right now.",
    "Tired of opening twenty tabs just to find one fact? We can simplify things for you.",
    "Skip the ads and the pop-ups. Get straight to the heart of the matter.",
    "Stop searching and start knowing. A direct path to the information you’re looking for.",
    "Don’t get lost in a sea of blue links. One clear answer is all you need.",
    "Tired of scrolling through five pages of stories to find a recipe? We'll get straight to the point.",
    "Silence the noise of the internet. Find exactly what you’re looking for without the clutter.",
    "The direct route is always the best. Save yourself ten minutes of searching.",
    "Stop second-guessing your search terms. Just ask us in your own words.",
    "A simpler way to understand the world. No more endless clicking required.",
    "Don’t let a simple question turn into an hour of research. Get help and move on with your day.",
    "Your shortcut to clarity. Quit the \"searching for the search term\" cycle.",
    "Stop the \"just one more tab\" habit. Get the full story in one place.",
    "The antidote to information overload. Clear, concise, and exactly what you need.",
    "Find the needle without having to search the entire haystack. We’ve already done the hunting for you.",
    "Tired of those \"helpful\" articles that never actually help? Try a more direct approach.",
    "Stop fighting with search engines. Talk to someone who actually understands what you need.",
    "The end of the endless scroll. Get your answer and get back to your life.",
    "Why visit ten websites when one conversation is enough? Save your energy for better things.",
    "The internet is big and noisy. Let us find the signal for you.",
    "Stop sifting through outdated forum posts from 2008. Get a fresh answer that works today.",
    "One quick question instead of five different searches. The easiest way to stay informed.",
    "Don’t let your browser tabs slow you down. One answer is lighter than twenty websites.",
    "A cleaner, quieter way to find what you need. No distractions, just help.",
    "Quit the guessing game. Describe what you’re looking for, and we’ll find it.",
    "Stop wasting time on sites that are just trying to sell you something. Get the honest truth right here.",
    "Skip the \"top ten\" lists and get the specific help you need. Tailored just for you.",
    "Tired of being told \"maybe you meant this instead\"? We listen better than a search bar.",
    "The simplest way to get unstuck. No more dead ends in your research.",
    "Get the bottom line without having to read between the lines. Plain talk for your practical questions.",
    "Stop the digital hunt. The answer you’ve been looking for is right here.",
    "Don't let a search engine decide what you should read. Get a direct response that matters.",
    "Tired of those websites that make you wait for the page to load? Speed up your life with a quick chat.",
    "A breath of fresh air for your browser. Clear the clutter and get the clarity you deserve.",
    "The most direct way to get through your to-do list. Find what you need and move on.",
    "Stop searching for \"how to\" and just get it done. We'll guide you through the steps.",
    "No more \"are you a robot?\" tests. Just human help for your human questions.",
    "The end of the SEO-cluttered search page. Real answers for real people.",
    "Stop the comparison trap. Get the facts you need to make a choice without the bias.",
    "Why search when you can just find? The ultimate shortcut for your busy morning.",
    "Don't get buried under a pile of links. Stay on top of things with one clear response.",
    "The smartest way to spend your lunchtime. Get the answers you need and still have time for a walk.",
    "A quiet evening is better than a night of research. Get the final word on that topic you've been wondering about.",
    "Stop the frantic clicking. Breathe in, ask your question, and breathe out.",
    "The internet shouldn't feel like a chore. Let us make it feel like a resource again.",
    "Tired of finding everything except what you actually need? We’re much more specific.",
    "Replace your bookmarks with a conversation. Everything you need is right here.",
    "Stop the tab-switching madness. Focus on the answer, not the navigation.",
    "The most thoughtful way to find the truth. No noise, just knowledge.",
    "Why search the whole world when you only need one piece of it? We'll help you find that piece.",
    "Skip the \"sponsored results\" at the top of the page. Get the actual answer right away.",
    "Stop being a search expert and start being an expert in your own life. We've got the info covered.",
    "Tired of clicking \"Next Page\" and still not finding it? Let’s try a different way.",
    "One clear window instead of a dozen cluttered ones. The simplest way to use the web.",
    "Stop the late-night search spiral. Get the answer you need so you can finally go to sleep.",
    "The internet doesn't have to be overwhelming. We'll filter the noise for you.",
    "A direct line to the help you need. No more jumping through hoops.",
    "Stop searching for the right phrasing. Whatever you type, we'll understand.",
    "The quickest way to bridge the gap between \"I don't know\" and \"I've got it.\" Start here.",
    "Tired of those sites that hide the answer at the bottom of the page? We put it right at the top.",
    "Stop the \"I'll find it eventually\" stress. Find it now and feel better.",
    "The most respectful way to use your time. No fluff, just help.",
    "Don't get distracted by the sidebars. Stay focused on what you actually came for.",
    "Why wander the woods when there's a clear path right here? Follow us to the answer.",
    "The end of the \"I can't find it\" frustration. We're here to help you cross it off your list.",
    "Stop being your own research assistant. Let us do the digging while you do the thinking.",
    "Tired of the internet feeling like a maze? We have the map.",
    "Clear the mental space for something better. Get your answer in one try.",
    "Stop the search-refresh-search cycle. One question, one answer, one success.",
    "A more human way to navigate the information age. Just talk to us.",
    "Skip the \"we use cookies\" banners and the \"subscribe now\" pop-ups. Get the info and go.",
    "Stop searching for a needle in a haystack. We’ll just hand you the needle.",
    "Tired of searching for \"the best\" and getting a hundred ads? We'll help you decide for yourself.",
    "Don't let the internet waste your afternoon. Get what you need and get back to what matters.",
    "The most efficient way to clear your head. Find the answer and find your peace.",
    "Stop the digital chase. The information you need is waiting for you.",
    "Why look in a thousand places when everything is in one? Simplify your digital life.",
    "Tired of those \"you might also like\" distractions? We only care about what you asked.",
    "Stop the \"where did I see that?\" headache. We'll help you get it right the first time.",
    "The cleanest way to learn something new. One topic, one conversation, total clarity.",
    "Don't get lost in the footnotes. Get the big picture right away.",
    "Stop the frantic hunt for information. Let the information come to you.",
    "The most direct way to feel informed. No more digging required.",
    "Tired of the internet making you feel more confused? Let’s clear things up together.",
    "Stop the \"I have too many tabs open\" stress. Close them all and just talk to us.",
    "The smartest shortcut on the web. Save time for the things you actually enjoy.",
    "Why settle for a list of links when you can have a conversation? The future of curiosity is here.",
    "Stop the endless clicking and the endless scrolling. The answer is right in front of you.",
    "Don't let the internet overwhelm your morning. Get one clear thought and get going.",
    "Tired of the internet feeling like a giant library with no librarian? We're here to help you find the right book.",
    "Stop the search and start the discovery. Everything is simpler when you just ask.",
    "The most peaceful way to find the facts. No noise, no ads, just help.",
    "Don't get stuck in the search results. Step through the door to the actual answer.",
    "Why spend half an hour searching when you can spend thirty seconds asking? The math is easy.",
    "Stop the digital noise from taking over your day. Get the signal you need.",
    "Tired of the same old links that never change? Try a fresh way to find the truth.",
    "One simple box, one clear answer. The easiest way to know.",
    "Don’t let the internet make your life harder. We’re here to make it easier.",
    "Stop the \"I'll just search it later\" procrastination. Find it now and enjoy your evening.",
    "The ultimate antidote to the searching blues. Get help and get happy."
];
